### ISSUE TITLE
Unwrap path parameters into the Context

### ISSUE THREAD

**Issue by hubslave** [guregu/kami#10]
Perhaps this is a matter of taste, but I think it would make the package more general if path parameters could (also) be retrieved via the standard `ctx.Value(key).(string)` idiom, not just through `kami.Param(ctx, key)`.

**Comment by guregu** [comment]
From what I understand the standard way is to not expose the keys or use `ctx.Value()` directly, and instead create helper functions in your package, like so: [Go Blog link](https://blog.golang.org/context#TOC_3.2.)

 What would you use for the type of `key`? I could change how they are stored and expose them via something like:
```go
type ParamKey string
```
and you could use `ctx.Value(kami.ParamKey("whatever")).(string)`, but you would still have to import kami to access them. This would let you manipulate parameters in your middleware though, which could be useful. Using plain strings could conflict with other people's context usage, so I can't have that by default. 

One thing kami is definitely missing right now is some way to get *all* the parameters of a request. If that existed, you can easy add a middleware that (for example) adds all your parameters with string keys to your context. 

I could add a `kami.Params(ctx)` function that returns all the parameters in a context, or I could add a `kami/params` subpackage that provides a more useful API for setting/retrieving arbitrary parameters.

**Comment by hubslave** [comment]
Ah. Hm. My motivation was indeed being able to extract path parameters from the context without importing kami, but if context keys are indeed intended to be a package's implementation detail, then I believe `kami.Param` is the best design you can have. An API for arbitrary path parameter manipulation could also be useful, but it's out of scope for my needs.
