### ISSUE TITLE
Add kami to TechEmpowered framework benchmarks

### ISSUE THREAD

**Issue by someone1** [guregu/kami#18]
I've copied the go-raw/goji implementations and modified it for kami here: https://github.com/someone1/FrameworkBenchmarks/tree/master/frameworks/Go/kami

I was wondering if there was any interest in tweaking this so that it uses kami in a more "production" kind of way. As you can see I added a middleware to add the Server response header vs setting per handler as it seems like the way you'd tackle this in any framework. I don't know if there's really more to do here but I thought I'd ask before putting in a PR. I don't really use the context object in anyway, would it make sense to use it to get the database object vs using a global variable in an actual production application?

**Comment by guregu** [comment]
Looks good... I'm not sure how fair the other benchmarks are, but as long as they are on the same page.
As far as putting global stuff in your context, that's up to you. Some people say it's an anti-pattern to store configuration etc in the context and you should only put request-specific stuff in there, but I think it comes down to personal preference.

**Comment by guregu** [comment]
Looks like we're in the latest benchmarks, thanks a lot!
