### ISSUE TITLE
Allow telling the mux its handler pattern

### ISSUE THREAD

**Issue by urandom** [guregu/kami#19]
Hi,

When using kami with its Handler function, or using an independent mux, you currently have to repeat the Handler pattern where the mux is attached to in all its subsequent routes. This, while annoying, also also causes whoever is building the routes to actually know beforehand where the mux itself will be attached. That might not be possible (i.e. if you are building some sort of component that others are meant to use wherever they like).

Instead, give the mux (and kami) the ability to receive the handler pattern:
```
kami.Pattern = "/admin/"
...
mux.Pattern = "/web/"
```
and instead of writing "/admin/memstats", just write "/memstats" as the route.

**Comment by guregu** [comment]
Hello,
I wouldn't mind adding this, but couldn't you just use [`http.StripPrefix`](https://godoc.org/net/http#StripPrefix)?

**Comment by urandom** [comment]
I actually tried that before writing the bug, thinking it would be that easy. IIRC, I tried wrapping the kami.Handler() around it, but the routes still didn't match. Although I must admit, that might not have been the proper chaining, but it's not immediately obvious how I'm supposed to chain the kami handler and StripPrefix one

**Comment by guregu** [comment]
@urandom I agree it's pretty confusing. I recommend using http.DefaultServeMux to serve all your stuff, which is what kami.Serve() does in the background. Here's an example of composing the global router with another mux: https://gist.github.com/guregu/8317af56ef26aed59773

**Comment by urandom** [comment]
Hi,

After I saw your gist, I saw that my error was that the StripPrefix pattern had a trailing slash. Without it, it works excellent.
