### ISSUE TITLE
Access path params without starting the kami server

### ISSUE THREAD

**Issue by rybit** [guregu/kami#26]
Hi - 

I am trying to test the methods I have attached to paths, but I'd rather do it without firing up the whole web server. 

I have been using the httptest and making my contexts manually but I can't seem to add a path parameter. I think it is because there is no way to add one in the kami api.

In code what I am doing looks like this:

``` go
// in the test
 ctx := testContext(token("stranger", "stranger-danger@email.com", nil))
 recorder := httptest.NewRecorder()
 req, _ := http.NewRequest("GET", fmt.Sprintf("https://not-real/%s", testUser.ID), nil)

// .... test setup
 api.GetThingy(ctx, recorder, req)
/// validate 
```
and in the api method `GetThingy` I do a `kami.Params(ctx, "id")` and the route is defined as `kame.Get("/thingy/:id", api.GetThingy)`

I could start the webserver up and actually pass through all the middlewares and such, but I'd like to just test the method directly without all the HTTP overhead.

**Comment by guregu** [comment]
Hello, have you tried something like:
`kami.Handler().ServeHTTP(recorder, req)`
?

This will run it through all the kami stuff without having to start the webserver.

**Comment by guregu** [comment]
I agree that we could use an API to manipulate path parameters though. I think I will either add a params package or a SetParam function.

**Comment by guregu** [comment]
Done, I wrote some warnings in the release notes. Using it for testing is totally fine.
