### ISSUE TITLE
Afterware should follow same rules as middleware

### ISSUE THREAD

**Issue by asgaines** [guregu/kami#34]
After loading both a middleware and afterware layer to the same path, I noticed that OPTIONS requests were not being fed through the middleware layer, but were being processed by the afterware layer. Since the afterware layer was dependent upon setup in the middleware, this caused errors which required a patch by checking against the request method in the afterware.

The rules for determining the processing of a request should be identical for middleware and afterware.

**Comment by guregu** [comment]
Hello, thanks for the report. Sounds like a bug to me.
I'm not able to reproduce this though, for example the following test case passes:
```go
func TestOptionsMiddleware(t *testing.T) {
	kami.Reset()
	ok := false
	kami.Use("/hello/", func(ctx context.Context, w http.ResponseWriter, r *http.Request) context.Context {
		return context.WithValue(ctx, "hello", "world")
	})
	kami.Options("/hello/", func(ctx context.Context, w http.ResponseWriter, r *http.Request) {})
	kami.After("/hello/", func(ctx context.Context, w http.ResponseWriter, r *http.Request) context.Context {
		if ctx.Value("hello").(string) == "world" {
			ok = true
		}
		return ctx
	})

	expectResponseCode(t, "OPTIONS", "/hello/", http.StatusOK)
	if !ok {
		t.Error("middleware did not run")
	}
}
```
If you could provide a failing test case it would help in debugging.

**Comment by asgaines** [comment]
Thanks for the reply. I tried recreating the conditions but it all seemed OK this time around... I'm sure you know how it is.

My best guess is that I might've forgotten the trailing `/` on middleware, but remembered it on the afterware layer.

If it crops up again, I'll pin it down and create a new issue with detailed information.

Btw, thanks for a great project ✌️
